apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-app-deployment
spec:
  selector:
    matchLabels:
      app: wil-app
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
      - name: wil-app-img
        image: wil42/playground:v1
